### PR TITLE
Set Content-Length automatically

### PR DESCRIPTION
**Pull request by kiyolee**
If header "Content-Length" is added and value set to "auto", "Content-Length" is automatically replaced with body length.
Much handier than manually figure out content length every time.

### CODE REVIEW

**Comment by jcoc611** [comment]
Thanks for the PR! Should we also set `Content-Length` if not otherwise specified in the headers?

**Comment by kiyolee** [comment]
In general, Content-Length should always be set for POST. However, web server should still work without Content-Length. So that is a valid test case to not providing Content-Length, although that is a relatively rare case and indeed not that useful.
If you agree Content-Length should always be set, I can change my PR to do that. I think that will make VSConnect less surprising to use with default settings. I was actually surprised that I need to set Content-Length manually.

**Comment by jcoc611** [comment]
Actually, that's a good point about it being a good test case. I think it's best if we only compute it when it is equal to `auto`, but also have that be part of the default headers. That way, the default experience is reasonable, but there is also an easy way to send a request without `Content-Length`.

Could you add `['Content-Length', 'auto']` to the default headers? Happy to merge the PR in after that.

**Comment by kiyolee** [comment]
Added the default header and take the opportunity to improve headers handling. Please refer to last commit comment for details.

**Pull request merged**
